version: '3.8'
services:
  postgres:
    image: postgres
    container_name: my-compose-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pddata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: my-compose-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  pddata: